-- 코드를 입력하세요
WITH FAV_RK AS(
    SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES,
    RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rk
    FROM REST_INFO)

SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM FAV_RK
WHERE rk=1
ORDER BY FOOD_TYPE DESC;