-- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME,
#     CASE SEX_UPON_INTAKE LIKE "%Neutered%" or "%Spayerd%" WITH "O" ELSE "X" AS "중성화"
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID DESC

SELECT ANIMAL_ID, NAME,
    CASE 
        WHEN SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
        ELSE 'X'
    END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;
